services:
    sonata.admin.categoria:
        class: PruebaBundle\Admin\CategoriaAdmin
        tags:
            - {name: sonata.admin, manager_type:orm, group:'Prueba', label:'categoria'}
        arguments:
            - ~
            - PruebaBundle\Entity\Categoria
            - ~
        calls:
            - [setTranslationDomain, [GestionBundle]]

    sonata.admin.producto:
            class: PruebaBundle\Admin\ProductoAdmin
            tags:
                - {name: sonata.admin, manager_type:orm, group:'Prueba', label:'Producto'}
            arguments:
                - ~
                - PruebaBundle\Entity\Producto
                - ~
            calls:
                - [setTranslationDomain, [GestionBundle]]

    sonata.admin.seleccion:
                class: PruebaBundle\Admin\SeleccionAdmin
                tags:
                    - {name: sonata.admin, manager_type:orm, group:'Prueba', label:'Seleccion Producto'}
                arguments:
                    - ~
                    - PruebaBundle\Entity\Seleccion
                    - ~
                calls:
                    - [setTranslationDomain, [GestionBundle]]
