<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * cargosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cargosRepository extends EntityRepository
{
}
