<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * personalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personalRepository extends EntityRepository
{
	public function getPersonal($id_dpto)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT per.email FROM GestionBundle:Personal per"
                ." WHERE per.dpto = :id_dpto"
            )->setParameter("id_dpto", $id_dpto)
            ->getResult()
            ;
    }
}
