<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlanosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanosRepository extends EntityRepository
{
    public function getPlanosProyecto($id_proyecto)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT pln FROM GestionBundle:Planos pln"
                ." WHERE pln.proyecto = :id_pjd"
            )->setParameter("id_pjd", $id_proyecto)
            ->getResult()
            ;
    }
}
