<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProyectosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectosRepository extends EntityRepository
{
    public function getProyecto($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT pj FROM GestionBundle:Proyectos pj"
                . " WHERE pj.id = :id"
            )
            ->setParameter("id", $id)
            ->setMaxResults(1)
            ->getResult();
    }

    public function getProyectos()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT pj FROM GestionBundle:Proyectos pj"
                ." WHERE pj.estado = 1"
            )
            ->getResult();
    }

}
