<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * proyectoimgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class proyectoimgRepository extends EntityRepository
{

    public function getImagenesProyecto($id_proyecto)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT imgp FROM GestionBundle:Proyectoimg imgp"
                ." WHERE imgp.proyecto = :id_pjd"
            )->setParameter("id_pjd", $id_proyecto)
            ->setMaxResults(4)
            ->getResult()
            ;
    }

    public function getAllImagenesProyecto($id_proyecto)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT imgp FROM GestionBundle:Proyectoimg imgp"
                ." WHERE imgp.proyecto = :id_pjd"
            )->setParameter("id_pjd", $id_proyecto)
            ->getResult()
            ;
    }
}
