<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * proyectoimgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends EntityRepository
{

    public function getSliderProyecto($id_proyecto)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT img FROM GestionBundle:Slider img"
                ." WHERE img.proyecto = :id_pjd"
            )->setParameter("id_pjd", $id_proyecto)
            ->getResult()
            ;
    }
}
