<?php

namespace PruebaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SeleccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeleccionRepository extends EntityRepository
{
}
