services:
    app.admin.car:
        class: GestionBundle\Admin\CurriculumsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Demo, label: demoCurriculum }
        arguments:
            - null
            - GestionBundle\Entity\Curriculums
            - GestionBundle:CRUD